"""Create mutual_fund_schemes table

Revision ID: 590c71730e02
Revises: 70b877cce60f
Create Date: 2025-01-04 14:34:29.412232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590c71730e02'
down_revision: Union[str, None] = '70b877cce60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scheme_id', sa.Integer(), nullable=True),
    sa.Column('units_invested', sa.Float(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['mutual_fund_schemes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###
