"""Create mutual_fund_schemes table

Revision ID: 70b877cce60f
Revises: 67230d5e7c27
Create Date: 2025-01-04 14:24:55.926036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b877cce60f'
down_revision: Union[str, None] = '67230d5e7c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_index(op.f('ix_families_name'), 'families', ['name'], unique=False)
    op.create_table('mutual_fund_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_no', sa.Integer(), nullable=True),
    sa.Column('scheme_name', sa.String(), nullable=True),
    sa.Column('amc_code', sa.String(), nullable=True),
    sa.Column('amc_scheme_code', sa.String(), nullable=True),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('minimum_purchase_amount', sa.Float(), nullable=True),
    sa.Column('purchase_allowed', sa.Boolean(), nullable=True),
    sa.Column('redemption_allowed', sa.Boolean(), nullable=True),
    sa.Column('purchase_cutoff_time', sa.String(), nullable=True),
    sa.Column('redemption_cutoff_time', sa.String(), nullable=True),
    sa.Column('switch_flag', sa.Boolean(), nullable=True),
    sa.Column('sip_flag', sa.Boolean(), nullable=True),
    sa.Column('swp_flag', sa.Boolean(), nullable=True),
    sa.Column('lock_in_period_flag', sa.Boolean(), nullable=True),
    sa.Column('lock_in_period', sa.Integer(), nullable=True),
    sa.Column('exit_load_flag', sa.Boolean(), nullable=True),
    sa.Column('exit_load', sa.Float(), nullable=True),
    sa.Column('amc_active_flag', sa.String(), nullable=True),
    sa.Column('settlement_type', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutual_fund_schemes_id'), 'mutual_fund_schemes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutual_fund_schemes_id'), table_name='mutual_fund_schemes')
    op.drop_table('mutual_fund_schemes')
    op.drop_index(op.f('ix_families_name'), table_name='families')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
