"""Update MutualFundScheme model

Revision ID: e122ce2b648b
Revises: 590c71730e02
Create Date: 2025-01-04 15:18:47.841402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e122ce2b648b'
down_revision: Union[str, None] = '590c71730e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_investments_id', table_name='investments')
    op.drop_table('investments')
    op.add_column('mutual_fund_schemes', sa.Column('scheme_code', sa.Integer(), nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('isin_div_payout_growth', sa.String(), nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('isin_div_reinvestment', sa.String(), nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('net_asset_value', sa.Float(), nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('scheme_type', sa.String(), nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('scheme_category', sa.String(), nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('mutual_fund_family', sa.String(), nullable=True))
    op.create_index(op.f('ix_mutual_fund_schemes_scheme_code'), 'mutual_fund_schemes', ['scheme_code'], unique=True)
    op.drop_column('mutual_fund_schemes', 'redemption_allowed')
    op.drop_column('mutual_fund_schemes', 'unique_no')
    op.drop_column('mutual_fund_schemes', 'exit_load_flag')
    op.drop_column('mutual_fund_schemes', 'settlement_type')
    op.drop_column('mutual_fund_schemes', 'purchase_cutoff_time')
    op.drop_column('mutual_fund_schemes', 'start_date')
    op.drop_column('mutual_fund_schemes', 'face_value')
    op.drop_column('mutual_fund_schemes', 'isin')
    op.drop_column('mutual_fund_schemes', 'sip_flag')
    op.drop_column('mutual_fund_schemes', 'amc_code')
    op.drop_column('mutual_fund_schemes', 'amc_active_flag')
    op.drop_column('mutual_fund_schemes', 'lock_in_period')
    op.drop_column('mutual_fund_schemes', 'swp_flag')
    op.drop_column('mutual_fund_schemes', 'redemption_cutoff_time')
    op.drop_column('mutual_fund_schemes', 'end_date')
    op.drop_column('mutual_fund_schemes', 'switch_flag')
    op.drop_column('mutual_fund_schemes', 'exit_load')
    op.drop_column('mutual_fund_schemes', 'purchase_allowed')
    op.drop_column('mutual_fund_schemes', 'lock_in_period_flag')
    op.drop_column('mutual_fund_schemes', 'amc_scheme_code')
    op.drop_column('mutual_fund_schemes', 'minimum_purchase_amount')
    op.add_column('users', sa.Column('family_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'family_id')
    op.add_column('mutual_fund_schemes', sa.Column('minimum_purchase_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('amc_scheme_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('lock_in_period_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('purchase_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('exit_load', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('switch_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('redemption_cutoff_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('swp_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('lock_in_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('amc_active_flag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('amc_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('sip_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('isin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('face_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('purchase_cutoff_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('settlement_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('exit_load_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('unique_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mutual_fund_schemes', sa.Column('redemption_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mutual_fund_schemes_scheme_code'), table_name='mutual_fund_schemes')
    op.drop_column('mutual_fund_schemes', 'mutual_fund_family')
    op.drop_column('mutual_fund_schemes', 'scheme_category')
    op.drop_column('mutual_fund_schemes', 'scheme_type')
    op.drop_column('mutual_fund_schemes', 'date')
    op.drop_column('mutual_fund_schemes', 'net_asset_value')
    op.drop_column('mutual_fund_schemes', 'isin_div_reinvestment')
    op.drop_column('mutual_fund_schemes', 'isin_div_payout_growth')
    op.drop_column('mutual_fund_schemes', 'scheme_code')
    op.create_table('investments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('units_invested', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('purchase_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['mutual_fund_schemes.id'], name='investments_scheme_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='investments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='investments_pkey')
    )
    op.create_index('ix_investments_id', 'investments', ['id'], unique=False)
    # ### end Alembic commands ###
